# Ejercicio 41

Sumar, restar, multiplicar y dividir escalares.

## Solución:

In [1]:
import numpy as np

In [2]:
np.add(1, 3)

4

In [3]:
np.subtract(3, 1)

2

In [4]:
np.multiply(5, 3)

15

In [5]:
np.divide(16, 8)

2.0

# Ejercicio 42

Calcular el logaritmo de la suma de la exponenciación de dos valores de entrada. También aplicar logaritmo en base dos para los mismos valores de entrada.

## Solución:

In [6]:
import numpy as np

log1 = np.log(1e-30)
log2 = np.log(2.3e-30)

In [7]:
np.logaddexp(log1, log2)

-67.88363032134893

In [8]:
np.logaddexp2(log1, log2)

-67.60180712062458

## Ejercicio 43

Dividir cada elemento de un arreglo por un número arbitrario.

## Solución:

In [9]:
import numpy as np

In [10]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.true_divide(a, 5)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

# Ejercicio 44

Dividir cada elemento de un arreglo por un número y redondear hacia abajo el resultado.

## Solución:

In [12]:
import numpy as np

In [13]:
arreglo = np.array([2, 3, 5, 7])

arreglo

array([2, 3, 5, 7])

In [14]:
np.floor_divide(arreglo, 2.0)

array([1., 1., 2., 3.])

# Ejercicio 45

Elevar a un número arbitrario cada elemento de un arreglo.

## Solución:

In [15]:
import numpy as np

In [16]:
a = np.arange(7)

a

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
np.power(a, 3)

array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

# Ejercicio 46

Calcular el residuo al dividir los elementos (uno a uno) de un arreglo por un número arbitrario.

## Solución:

In [18]:
import numpy as np

In [19]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [20]:
np.remainder(a, 3)

array([0, 1, 2, 0, 1], dtype=int32)

# Ejercicio 47

Calcular el valor absoluto de cada elemento de un arreglo.

## Solución:

In [21]:
import numpy as np

In [22]:
a = np.array([-2, -13.5, 13, 8, -1])
a

array([ -2. , -13.5,  13. ,   8. ,  -1. ])

In [23]:
np.absolute(a)

array([ 2. , 13.5, 13. ,  8. ,  1. ])

# Ejercicio 48

Redondear cada elemento de un arreglo a una cantidad de decimales arbitraria.

## Solución:

In [24]:
import numpy as np

In [25]:
arreglo = np.array([3.141592, 2.718281, 1.41421])
arreglo

array([3.141592, 2.718281, 1.41421 ])

In [26]:
np.round(arreglo)

array([3., 3., 1.])

In [27]:
np.round(arreglo, decimals=1)

array([3.1, 2.7, 1.4])

In [28]:
np.round(arreglo, decimals=5)

array([3.14159, 2.71828, 1.41421])

# Ejercicio 49

Rodendar los elementos de un arreglo al entero más cercano.

## Solución:

In [29]:
import numpy as np

In [30]:
a = np.array([-1.3, 2.7, 3.8, 3.3, 5.1, -4.7])
a

array([-1.3,  2.7,  3.8,  3.3,  5.1, -4.7])

In [31]:
np.rint(a)

array([-1.,  3.,  4.,  3.,  5., -5.])

# Ejercicio 50

Redondear hacia abajo, arriba, y truncar cada elemento de un arreglo.

## Solución:

In [32]:
import numpy as np

In [33]:
a = np.array([2.3, -1.5, -2.3, 0.8, 9.4, -7.9])
a

array([ 2.3, -1.5, -2.3,  0.8,  9.4, -7.9])

In [34]:
np.floor(a)

array([ 2., -2., -3.,  0.,  9., -8.])

In [35]:
np.ceil(a)

array([ 3., -1., -2.,  1., 10., -7.])

In [36]:
np.trunc(a)

array([ 2., -1., -2.,  0.,  9., -7.])

# Ejercicio 51

Multiplicar dos matrices con valores arbitrarios.

## Solución:

In [37]:
import numpy as np

In [38]:
a = np.arange(0, 15).reshape((5, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [39]:
b = np.arange(0, 6).reshape((3, 2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
np.dot(a, b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

# Ejercicio 52

Multiplicar dos arreglos que contienen números complejos.

## Solución:

In [41]:
import numpy as np

In [42]:
x = np.array([3+5j, 7+4j])
x

array([3.+5.j, 7.+4.j])

In [43]:
y = np.array([2+3j, 8+2j])
y

array([2.+3.j, 8.+2.j])

In [44]:
np.vdot(x, y)

(85-19j)

# Ejercicio 53

Multiplicar una matriz por un arreglo.

## Solución:

In [45]:
import numpy as np

In [46]:
matriz = np.arange(15).reshape((3, 5))
matriz

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
arreglo = np.arange(5)
arreglo

array([0, 1, 2, 3, 4])

In [48]:
np.inner(matriz, arreglo)

array([ 30,  80, 130])

# Ejercicio 54

Calcular el producto cruz de dos vectores.

## Solución:

In [49]:
import numpy as np

In [50]:
x = np.array([1, 2, 3])
y = np.array([9, 8, 7])

In [51]:
np.cross(x, y)

array([-10,  20, -10])

# Ejercicio 55

A partir de dos arreglos crear un producto de matrices.

## Solución:

In [52]:
import numpy as np

In [53]:
x = [[1, 2], [3, 4]]
y = [[5, 6], [7, 8]]

x,y

([[1, 2], [3, 4]], [[5, 6], [7, 8]])

In [54]:
np.matmul(x, y)

array([[19, 22],
       [43, 50]])

# Ejercicio 51

Encontrar las raíces de los polinomios:

a) $$x^{2}+6x+9$$
b) $$x^{4} − 11x^{3} + 9x^{2} + 11x – 10$$

## Solución:

In [55]:
import numpy as np

In [56]:
np.roots([1, 6, 9])

array([-3.+3.7252903e-08j, -3.-3.7252903e-08j])

$$x^{4} − 11x^{3} + 9x^{2} + 11x – 10$$

In [57]:
coeficientes = [1, -11, 9, 11, -1]

In [58]:
np.roots(coeficientes)

array([ 9.98986687,  1.63868971, -0.71409964,  0.08554306])

# Ejercicio 57

Encontrar el valor de los polinomios cuando $x=2$:

a) $$x^{2}+6x+9$$
b) $$x^{4} − 10x^{3} + 4x^{2} + 5x – 10$$

## Solución:

In [59]:
import numpy as np

In [60]:
np.polyval([1,6,9], 2)

25

In [61]:
np.polyval([1, -10, 4, 5, -10], 2)

-48

# Ejercicio 58

Aplicar las operaciones de suma, resta, multiplicación y división de polinomios.

a) $5x^{2}+10x+15$<br>
b) $15x^{2}+20x+25$

## Solución:

In [62]:
import numpy as np

coef_a = (5, 10, 15)
coef_b = (15, 20, 25)

In [63]:
np.polynomial.polynomial.polyadd(coef_a, coef_b)

array([20., 30., 40.])

In [64]:
np.polynomial.polynomial.polysub(coef_a, coef_b)

array([-10., -10., -10.])

In [65]:
np.polynomial.polynomial.polymul(coef_a, coef_b)

array([ 75., 250., 550., 550., 375.])

In [66]:
np.polynomial.polynomial.polydiv(coef_a, coef_b)

(array([0.6]), array([-4., -2.]))

# Ejercicio 59

Calcular el promedio de una matriz por cada dimensión.

## Solución:

In [67]:
import numpy as np

In [68]:
matriz = np.array([[5, 10], [12, 24]])
matriz

array([[ 5, 10],
       [12, 24]])

In [69]:
matriz.mean(axis=0)

array([ 8.5, 17. ])

In [70]:
matriz.mean(axis=1)

array([ 7.5, 18. ])

# Ejercicio 60

Calcular estadísticas elementales sobre un arreglo.

## Solución:

In [71]:
import numpy as np

In [72]:
a = np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
a.mean()

24.5

In [74]:
a.std()

14.430869689661812

In [75]:
a.var()

208.25

# Ejercicio 61

Calcular el seno, coseno y tangente de un arreglo (valores en radianes).

## Solución:

In [76]:
import numpy as np

In [77]:
radianes = [np.pi/6, np.pi/4, np.pi/3, np.pi/2]

In [78]:
np.sin(radianes)

array([0.5       , 0.70710678, 0.8660254 , 1.        ])

In [79]:
np.cos(radianes)

array([8.66025404e-01, 7.07106781e-01, 5.00000000e-01, 6.12323400e-17])

In [80]:
np.tan(radianes)

array([5.77350269e-01, 1.00000000e+00, 1.73205081e+00, 1.63312394e+16])