# Ejercicio 165

Generar 10 números aleatorios a partir de una distribución normal.

## Solución:

In [1]:
import numpy as np

In [2]:
arreglo = np.random.normal(size=10)

arreglo

array([-1.06887592, -0.03187524,  1.47892606, -0.86922781, -1.40688985,
       -0.75154757, -0.36604557, -2.2337027 , -0.20955504, -0.96075768])

# Ejercicio 166

Generar 10 valores enteros entre 1 y 30.

## Solución:

In [3]:
import numpy as np

In [4]:
np.random.randint(low=1, high=30, size=10)

array([12, 16,  2, 16, 25, 26, 29, 14,  8, 29])

# Ejercicio 167

Generar un panel (cubo) de tamaño 4x4x4 que contenga números aleatorios.

## Solución:

In [5]:
import numpy as np

In [6]:
panel = np.random.random((4, 4, 4))

panel

array([[[0.52496645, 0.58363829, 0.25871867, 0.60308887],
        [0.55205983, 0.44430436, 0.28395769, 0.36390762],
        [0.61522471, 0.04214838, 0.5762407 , 0.7670476 ],
        [0.09706712, 0.44673486, 0.13466259, 0.27555656]],

       [[0.10572225, 0.24891622, 0.4517817 , 0.90424005],
        [0.31199521, 0.09151868, 0.1002408 , 0.33490124],
        [0.65859154, 0.51291323, 0.13251564, 0.87291355],
        [0.08937208, 0.51476334, 0.22842358, 0.5489599 ]],

       [[0.57163393, 0.52050507, 0.23431743, 0.37602816],
        [0.92371347, 0.2981394 , 0.16040589, 0.57353333],
        [0.02034896, 0.53480865, 0.00571434, 0.06436409],
        [0.13440857, 0.54137006, 0.38006384, 0.75786673]],

       [[0.7479763 , 0.7830116 , 0.80539608, 0.05460244],
        [0.15371591, 0.27397267, 0.45498309, 0.75997692],
        [0.23887472, 0.25758288, 0.11397708, 0.44586347],
        [0.2009914 , 0.24877352, 0.49242981, 0.39066757]]])

# Ejercicio 168

Crear una matriz de 4x4 con elementos aleatorios, y obtener el mínimo y el máximo de sus elementos.

## Solución:

In [7]:
import numpy as np

In [8]:
m = np.random.random((4, 4))

m

array([[0.43565376, 0.76142883, 0.00153494, 0.72221542],
       [0.31560516, 0.46319064, 0.03310022, 0.62645212],
       [0.70661491, 0.37349807, 0.52730119, 0.14414834],
       [0.5374711 , 0.39477395, 0.84716902, 0.20019649]])

In [9]:
m.min()

0.0015349401501595361

In [10]:
m.max()

0.8471690190318865

# Ejercicio 169

Crear una matriz de 15x15, y luego extraer las primeras 7 filas y almacernarlas en una variable.

## Solución:

In [11]:
import numpy as np

In [12]:
m = np.random.rand(15, 15)

m

array([[0.64769422, 0.01280197, 0.10332379, 0.32472542, 0.53926875,
        0.35774078, 0.15711208, 0.91487455, 0.96151735, 0.8574861 ,
        0.2787421 , 0.97627813, 0.16413232, 0.77497004, 0.93129065],
       [0.87966714, 0.67802113, 0.52240717, 0.00129652, 0.24219206,
        0.29573666, 0.59375003, 0.9167803 , 0.83977965, 0.57015565,
        0.49405311, 0.60344976, 0.71880822, 0.42688501, 0.78744598],
       [0.23115814, 0.44284138, 0.559001  , 0.87296734, 0.83385501,
        0.76287263, 0.18725481, 0.93564721, 0.03235705, 0.06040263,
        0.36773658, 0.01834783, 0.25708776, 0.25396127, 0.99125592],
       [0.53412026, 0.54795275, 0.4190027 , 0.74076988, 0.52652915,
        0.77792548, 0.98081671, 0.29226625, 0.76875547, 0.75182905,
        0.62994052, 0.02348766, 0.33351113, 0.29116542, 0.34284718],
       [0.06004679, 0.3629819 , 0.45489988, 0.59510196, 0.64351631,
        0.62140415, 0.72591893, 0.04797569, 0.14897765, 0.24530517,
        0.84443655, 0.33352077, 0.01457049, 

In [13]:
m2 = m[0:7, :]

m2

array([[0.64769422, 0.01280197, 0.10332379, 0.32472542, 0.53926875,
        0.35774078, 0.15711208, 0.91487455, 0.96151735, 0.8574861 ,
        0.2787421 , 0.97627813, 0.16413232, 0.77497004, 0.93129065],
       [0.87966714, 0.67802113, 0.52240717, 0.00129652, 0.24219206,
        0.29573666, 0.59375003, 0.9167803 , 0.83977965, 0.57015565,
        0.49405311, 0.60344976, 0.71880822, 0.42688501, 0.78744598],
       [0.23115814, 0.44284138, 0.559001  , 0.87296734, 0.83385501,
        0.76287263, 0.18725481, 0.93564721, 0.03235705, 0.06040263,
        0.36773658, 0.01834783, 0.25708776, 0.25396127, 0.99125592],
       [0.53412026, 0.54795275, 0.4190027 , 0.74076988, 0.52652915,
        0.77792548, 0.98081671, 0.29226625, 0.76875547, 0.75182905,
        0.62994052, 0.02348766, 0.33351113, 0.29116542, 0.34284718],
       [0.06004679, 0.3629819 , 0.45489988, 0.59510196, 0.64351631,
        0.62140415, 0.72591893, 0.04797569, 0.14897765, 0.24530517,
        0.84443655, 0.33352077, 0.01457049, 

# Ejercicio 170

Crear una arreglo con 10 elementos y luego aleatorizar sus posiciones.

## Solución:

In [14]:
import numpy as np

In [15]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.random.shuffle(a)

In [17]:
a

array([4, 5, 2, 0, 7, 1, 9, 6, 3, 8])

In [18]:
np.random.permutation(10)

array([6, 3, 2, 9, 4, 5, 8, 1, 0, 7])

# Ejercicio 171

Normalizar una matriz de 5x5.

## Solución:

In [19]:
import numpy as np

In [20]:
m = np.random.random((5, 5))

m

array([[0.45399668, 0.14205697, 0.88039212, 0.34684498, 0.69620826],
       [0.30232685, 0.54419413, 0.74614654, 0.04591222, 0.12676902],
       [0.07012442, 0.96605491, 0.93108695, 0.18120784, 0.55140124],
       [0.80676556, 0.56427901, 0.08165361, 0.79809306, 0.9800152 ],
       [0.53560022, 0.59802936, 0.15079609, 0.81332161, 0.0995853 ]])

In [21]:
minimo = m.min()
maximo = m.max()

minimo, maximo

(0.045912217486786866, 0.9800151999399386)

In [22]:
m = (m - minimo) / (maximo - minimo)

In [23]:
m

array([[0.4368731 , 0.10292736, 0.89334893, 0.3221623 , 0.69617168],
       [0.2745036 , 0.5334336 , 0.74963289, 0.        , 0.08656091],
       [0.02592027, 0.98505487, 0.94762007, 0.14484016, 0.54114914],
       [0.81452833, 0.55493538, 0.0382628 , 0.80524402, 1.        ],
       [0.52423342, 0.59106667, 0.11228299, 0.82154689, 0.05745949]])

# Ejercicio 172

Generar arreglo con elementos aleatorios y ordernarlo de forma ascendente.

## Solución:

In [24]:
import numpy as np

In [25]:
a = np.random.random(15)

a

array([0.55146614, 0.17721642, 0.22621309, 0.2797245 , 0.36008521,
       0.25169087, 0.47399441, 0.31305991, 0.08142928, 0.69657589,
       0.27351075, 0.67119878, 0.22967499, 0.84229768, 0.20293851])

In [26]:
a.sort()

In [27]:
a

array([0.08142928, 0.17721642, 0.20293851, 0.22621309, 0.22967499,
       0.25169087, 0.27351075, 0.2797245 , 0.31305991, 0.36008521,
       0.47399441, 0.55146614, 0.67119878, 0.69657589, 0.84229768])

# Ejercicio 173

Encontrar el valor más cercano a un valor arbitrario.

## Solución:

In [28]:
import numpy as np

In [29]:
a = np.random.uniform(1, 20, 10)

a

array([ 8.47785611, 10.94464126,  3.98145678, 12.11036863,  1.48666639,
        5.52092679, 12.75839945, 13.74372606, 18.85691308,  9.88305897])

In [30]:
valor = 5

In [31]:
a.flat[np.abs(a - valor).argmin()]

5.520926786467988

# Ejercicio 174

Comprobar si dos arreglos aleatorios son iguales.

## Solución:

In [32]:
import numpy as np

In [33]:
a = np.random.randint(0, 2, 5)
a

array([1, 0, 1, 0, 1])

In [34]:
b = np.random.randint(0, 2, 5)
b

array([0, 0, 1, 0, 1])

In [35]:
np.allclose(a, b)

False

# Ejercicio 175

Generar un arreglo con valores aleatorios y reemplazar el valor mayor con -1.

## Solución:

In [36]:
import numpy as np

In [37]:
a = np.random.random(20)

a

array([0.50437848, 0.30733231, 0.87464564, 0.73424977, 0.95561016,
       0.31682677, 0.5963207 , 0.01177664, 0.03458831, 0.93280109,
       0.32989026, 0.1190464 , 0.68569338, 0.50855383, 0.69138014,
       0.76522328, 0.02500786, 0.29230836, 0.97599546, 0.25285782])

In [38]:
a.max()

0.975995464011742

In [39]:
a[a.argmax()] = -1

In [40]:
a

array([ 0.50437848,  0.30733231,  0.87464564,  0.73424977,  0.95561016,
        0.31682677,  0.5963207 ,  0.01177664,  0.03458831,  0.93280109,
        0.32989026,  0.1190464 ,  0.68569338,  0.50855383,  0.69138014,
        0.76522328,  0.02500786,  0.29230836, -1.        ,  0.25285782])

# Ejercicio 176

Encontrar el valor más frecuente en un arreglo.

## Solución:

In [41]:
import numpy as np

In [42]:
a = np.random.randint(0, 15, 20)

a

array([13,  1, 10,  2, 12,  5,  1, 14, 13,  1, 12,  6, 10, 12,  7, 14, 13,
        2, 14,  0])

In [43]:
np.bincount(a).argmax()

1

# Ejercicio 177

A partir de una matriz con coordenadas cartesianas realizar la conversión a coordendas polares.

## Solución:

In [44]:
import numpy as np

In [45]:
m = np.random.random((15, 2))

x = m[:,0]
y = m[:,1]

x

array([0.41041381, 0.03411976, 0.48700534, 0.43749638, 0.9339806 ,
       0.09443086, 0.36996966, 0.39159732, 0.03181983, 0.39569267,
       0.19028769, 0.34245803, 0.5873676 , 0.38191875, 0.24055526])

In [46]:
y

array([0.90913607, 0.35696928, 0.32965596, 0.53597949, 0.27502437,
       0.96376522, 0.89584455, 0.03760622, 0.01800424, 0.61130039,
       0.50310067, 0.66712238, 0.12477475, 0.60794484, 0.03090979])

In [47]:
r = np.sqrt(x**2 + y**2)

r

array([0.99748077, 0.35859619, 0.58808779, 0.69186494, 0.97363143,
       0.9683804 , 0.96923424, 0.3933989 , 0.03656028, 0.72819012,
       0.53788445, 0.74988651, 0.60047434, 0.71795463, 0.24253299])

In [48]:
t = np.arctan2(y, x)

t

array([1.14675156, 1.47550404, 0.59505668, 0.88622159, 0.28637088,
       1.4731269 , 1.17914701, 0.09573928, 0.51490645, 0.9963239 ,
       1.20919702, 1.09653681, 0.20931882, 1.00989   , 0.12779327])

# Ejercicio 178

Obtener los `n` números mayores en un arreglo.

## Solución:

In [49]:
import numpy as np

In [50]:
a = np.arange(15)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
np.random.shuffle(a)

a

array([ 0, 12, 14, 10,  7,  1,  4,  5, 13, 11,  6,  3,  9,  2,  8])

In [52]:
n = 3

In [53]:
a[np.argsort(a)[-n:]]

array([12, 13, 14])

# Ejercicio 179

Ordenar una matriz por diferentes ejes, y por la versión arreglo de sus elementos.

## Solución:

In [54]:
import numpy as np

In [55]:
m = np.array([[3, 2, 1], [8, 4, 3], [5, 6, 0]])

m

array([[3, 2, 1],
       [8, 4, 3],
       [5, 6, 0]])

In [56]:
np.sort(m, axis=0)

array([[3, 2, 0],
       [5, 4, 1],
       [8, 6, 3]])

In [57]:
np.sort(m)

array([[1, 2, 3],
       [3, 4, 8],
       [0, 5, 6]])

In [58]:
np.sort(m, axis=None)

array([0, 1, 2, 3, 3, 4, 5, 6, 8])

# Ejercicio 180

Crear un arreglo con elementos definidos a partir de una estructura arbitraria.

## Solución:

In [59]:
import numpy as np

In [60]:
estudiante = [('nombre', 'S15'), ('curso', int), ('nota', float)]

In [61]:
estudiantes = [('Edward', 1, 4.5), ('German', 2, 4.3), ('Paula', 1, 4.1)]
estudiantes

[('Edward', 1, 4.5), ('German', 2, 4.3), ('Paula', 1, 4.1)]

In [62]:
arrEstudiantes = np.array(estudiantes, dtype=estudiante)

In [63]:
arrEstudiantes

array([(b'Edward', 1, 4.5), (b'German', 2, 4.3), (b'Paula', 1, 4.1)],
      dtype=[('nombre', 'S15'), ('curso', '<i4'), ('nota', '<f8')])

In [64]:
np.sort(arrEstudiantes, order='nota')

array([(b'Paula', 1, 4.1), (b'German', 2, 4.3), (b'Edward', 1, 4.5)],
      dtype=[('nombre', 'S15'), ('curso', '<i4'), ('nota', '<f8')])

# Ejercicio 181

Crear una estructura de datos para representar a un estudiante, crear registros, y ordenar por el identificador de clase y nota.

## Solución:

In [65]:
import numpy as np

In [66]:
tipo_dato_estudiante = [('nombre', 'S15'), ('curso', int), ('nota', float)]
tipo_dato_estudiante

[('nombre', 'S15'), ('curso', int), ('nota', float)]

In [67]:
estudiantes = [('Edward', 1, 4.5), ('German', 2, 4.3), ('Daniela', 1, 4.4)]

estudiantes

[('Edward', 1, 4.5), ('German', 2, 4.3), ('Daniela', 1, 4.4)]

In [68]:
arreglo_estudiantes = np.array(estudiantes, dtype=tipo_dato_estudiante)

arreglo_estudiantes

array([(b'Edward', 1, 4.5), (b'German', 2, 4.3), (b'Daniela', 1, 4.4)],
      dtype=[('nombre', 'S15'), ('curso', '<i4'), ('nota', '<f8')])

In [69]:
np.sort(arreglo_estudiantes, order=['curso', 'nota'])

array([(b'Daniela', 1, 4.4), (b'Edward', 1, 4.5), (b'German', 2, 4.3)],
      dtype=[('nombre', 'S15'), ('curso', '<i4'), ('nota', '<f8')])

# Ejercicio 182

Obtener e imprimir los índices que describen el ordendamiento por múltiples columnas.

## Solución:

In [70]:
import numpy as np

In [71]:
edades = np.array([27, 21, 29, 34, 37, 19, 23, 24, 18, 31])
alturas = np.array([1.72, 1.65, 1.68, 1.55, 1.63, 1.73, 1.81, 1.69, 1.75, 1.83])

edades

array([27, 21, 29, 34, 37, 19, 23, 24, 18, 31])

In [72]:
alturas

array([1.72, 1.65, 1.68, 1.55, 1.63, 1.73, 1.81, 1.69, 1.75, 1.83])

In [73]:
indices = np.lexsort((edades, alturas))

In [74]:
indices

array([3, 4, 1, 2, 7, 0, 5, 8, 6, 9], dtype=int64)

In [75]:
for i in indices:
    print(edades[i], alturas[i])

34 1.55
37 1.63
21 1.65
29 1.68
24 1.69
27 1.72
19 1.73
18 1.75
23 1.81
31 1.83


# Ejercicio 183

Obtener los índices de ordenamiento de un arreglo.

## Solución:

In [76]:
import numpy as np

In [77]:
edades = np.array([13, 18, 1, 5, 8, 23, 27, 29, 31, 4])

edades

array([13, 18,  1,  5,  8, 23, 27, 29, 31,  4])

In [78]:
indices = np.argsort(edades)

In [79]:
indices

array([2, 9, 3, 4, 0, 1, 5, 6, 7, 8], dtype=int64)

In [80]:
edades[8]

31

# Ejercicio 184

Ordenar un arreglo con elementos imaginarios, primero ordenar por la parte real y luego  por la parte imaginaria.

## Solución:

In [81]:
import numpy as np

In [82]:
complejos = [3+5j, 2+3j, -5-1j, 8+2j, 7+1j, 8+3j]

complejos

[(3+5j), (2+3j), (-5-1j), (8+2j), (7+1j), (8+3j)]

In [83]:
np.sort_complex(complejos)

array([-5.-1.j,  2.+3.j,  3.+5.j,  7.+1.j,  8.+2.j,  8.+3.j])

# Ejercicio 185

Ordenar los primeros 10 elementos de un arreglo.

## Solución:

In [84]:
import numpy as np

In [85]:
arreglo = np.random.random(20)

arreglo

array([0.24983518, 0.31562052, 0.45660906, 0.1810038 , 0.28470359,
       0.655801  , 0.84771262, 0.06633803, 0.82696248, 0.75064789,
       0.59740559, 0.69638157, 0.66890359, 0.44369222, 0.29958995,
       0.4743603 , 0.76020997, 0.99911113, 0.00927436, 0.68023649])

In [86]:
arreglo[np.argpartition(arreglo, range(10))]

array([0.00927436, 0.06633803, 0.1810038 , 0.24983518, 0.28470359,
       0.29958995, 0.31562052, 0.44369222, 0.45660906, 0.4743603 ,
       0.59740559, 0.69638157, 0.66890359, 0.84771262, 0.655801  ,
       0.75064789, 0.76020997, 0.99911113, 0.82696248, 0.68023649])

# Ejercicio 186

Ordenar los elementos a partir de una ubicación dada.

## Solución:

In [87]:
import numpy as np

In [88]:
a = np.array([70, 50, 20, 30, -11, 60, 50, 40])
a

array([ 70,  50,  20,  30, -11,  60,  50,  40])

In [89]:
np.partition(a, 4)

array([-11,  30,  20,  40,  50,  50,  60,  70])