# Ejercicio 148

Computar la multiplicación de dos matrices arbitrarias.

## Solución:

In [1]:
import numpy as np

In [2]:
a = [[2, 3], [5, 7]]
a

[[2, 3], [5, 7]]

In [3]:
b = [[4, 2], [3, 5]]
b

[[4, 2], [3, 5]]

In [4]:
np.dot(a, b)

array([[17, 19],
       [41, 45]])

# Ejercicio 149

Calcular el producto externo de dos vectores.

## Solución:

In [5]:
import numpy as np

In [6]:
a = [[2, 2], [1, 2]]
b = [[0, 1], [4, 0]]

a

[[2, 2], [1, 2]]

In [7]:
b

[[0, 1], [4, 0]]

In [8]:
np.outer(a, b)

array([[0, 2, 8, 0],
       [0, 2, 8, 0],
       [0, 1, 4, 0],
       [0, 2, 8, 0]])

# Ejercicio 150

Computar el producto cruz entre dos vectores arbitrarios.

## Solución:

In [9]:
import numpy as np

In [10]:
p = [[1, 3], [4, 3]]
q = [[5, 9], [3, 2]]

p

[[1, 3], [4, 3]]

In [11]:
q

[[5, 9], [3, 2]]

In [12]:
np.cross(p, q)

array([-6, -1])

In [13]:
np.cross(q, p)

array([6, 1])

# Ejercicio 151

Computar el determinante de una matriz.

## Solución:

In [14]:
import numpy as np

In [15]:
m = np.array([[2, 3, 4], [5, 7, 8], [2, 3, 5]])

m

array([[2, 3, 4],
       [5, 7, 8],
       [2, 3, 5]])

In [16]:
np.linalg.det(m)

-0.9999999999999991

# Ejercicio 152

Calcula la suma de Einstein para dos vectores.

## Solución:

In [17]:
import numpy as np

In [18]:
a = np.array([2, 3, 4])
b = np.array([5, 3, 2])

a, b

(array([2, 3, 4]), array([5, 3, 2]))

In [19]:
np.einsum("n,n", a, b)

27

# Ejercicio 153

Computar el producto interno de dos vectores unidimensionales.

## Solución:

In [20]:
import numpy as np

In [21]:
a = np.array([2, 3, 5])
b = np.array([3, 8, 7])

a, b

(array([2, 3, 5]), array([3, 8, 7]))

In [22]:
np.inner(a, b)

65

# Ejercicio 154

Computar los valores y vectores propios de una matriz.

## Solución:

In [23]:
import numpy as np

In [24]:
m = np.array([[2, 5, 3], [9, 5, 8], [2, 3, 8]])

m

array([[2, 5, 3],
       [9, 5, 8],
       [2, 3, 8]])

In [25]:
valores, vectores = np.linalg.eig(m)

valores

array([14.70064048, -3.51408616,  3.81344568])

In [26]:
vectores

array([[-0.41722955, -0.64293927, -0.50177578],
       [-0.77650312,  0.76100543, -0.57155045],
       [-0.47218896, -0.08660156,  0.64926971]])

# Ejercicio 155

Calcular el producto de Kronecker entre dos arreglos.

## Solución:

In [27]:
import numpy as np

In [28]:
a = np.array([5, 4, 3])
b = np.array([7, 3, 2])

a, b

(array([5, 4, 3]), array([7, 3, 2]))

In [29]:
np.kron(a, b)

array([35, 15, 10, 28, 12,  8, 21,  9,  6])

# Ejercicio 156

Calcular el número de condición para una matriz dada.

## Solución:

In [30]:
import numpy as np

In [31]:
m = np.array([[2, 3, 4], [9, 5, 3], [8, 3, 1]])

m

array([[2, 3, 4],
       [9, 5, 3],
       [8, 3, 1]])

In [32]:
np.linalg.cond(m)

52.115439703156454

# Ejercicio 157

Computar la norma de un vector o una matriz.

## Solución:

In [33]:
import numpy as np

In [34]:
v = np.arange(1, 13)
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
np.linalg.norm(v)

25.495097567963924

In [36]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.linalg.norm(m)

16.881943016134134

# Ejercicio 158

Computar el determinante de una matriz arbitraria (nxn).

## Solución:

In [38]:
import numpy as np

In [39]:
m = np.array([[4, 3, 1], [8, 9, 3], [4, 7, 9]])
m

array([[4, 3, 1],
       [8, 9, 3],
       [4, 7, 9]])

In [40]:
np.linalg.det(m)

79.99999999999997

# Ejercicio 159

Computar el inverso de una matriz dada.

## Solución:

In [41]:
import numpy as np

In [42]:
m = np.array([[3, 2, 1], [7, 5, 3], [7, 4, 5]])
m

array([[3, 2, 1],
       [7, 5, 3],
       [7, 4, 5]])

In [43]:
np.linalg.inv(m)

array([[ 3.25, -1.5 ,  0.25],
       [-3.5 ,  2.  , -0.5 ],
       [-1.75,  0.5 ,  0.25]])

# Ejercicio 160

Computar la factorización QR de una matriz dada.

## Solución:

In [44]:
import numpy as np

In [45]:
m = np.array([[3, 7, 5], [7, 4, 5], [2, 3, 5]])
m

array([[3, 7, 5],
       [7, 4, 5],
       [2, 3, 5]])

In [46]:
np.linalg.qr(m)

(array([[-0.38100038,  0.86412575, -0.32882427],
        [-0.88900089, -0.44009378, -0.12647087],
        [-0.25400025,  0.24413962,  0.93588446]]),
 array([[-7.87400787, -6.98500699, -7.62000762],
        [ 0.        ,  5.02092396,  3.34085791],
        [ 0.        ,  0.        ,  2.40294658]]))

# Ejercicio 161

Computar la traza de una matriz.

## Solución:

In [47]:
import numpy as np

In [48]:
m = np.array([[3, 2, 1], [5, 7, 9], [8, 5, 1]])
m

array([[3, 2, 1],
       [5, 7, 9],
       [8, 5, 1]])

In [49]:
np.trace(m)

11

In [50]:
np.trace(m, -1)

10

# Ejercicio 162

Computar el factor de una matriz a partir de la descomposición en valores singulares.

## Solución:

In [51]:
import numpy as np

In [52]:
m = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)

m

array([[1., 0., 0., 0., 2.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.]], dtype=float32)

In [53]:
U, s, V = np.linalg.svd(m, full_matrices=False)

In [54]:
U

array([[ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.],
       [ 0.,  0.,  1.,  0.]], dtype=float32)

# Ejercicio 163

Computar la norma y el número de condición de Frobenius.

## Solución:

In [55]:
import numpy as np

In [56]:
m = np.arange(1, 17).reshape(4, 4)

m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [57]:
np.linalg.norm(m, 'fro')

38.67815921162743

In [58]:
np.linalg.cond(m, 'fro')

3.210478703559863e+18

# Ejercicio 164

Computar la matriz triangular inferior L usando la factorización de Cholesky.

## Solución

In [59]:
import numpy as np

In [60]:
m = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])

m

array([[  4,  12, -16],
       [ 12,  37, -43],
       [-16, -43,  98]])

In [61]:
np.linalg.cholesky(m)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])